2020-07-15 16:41:17.636851: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pbs/throng/km3net/software/aanet/master/lib:/pbs/throng/km3net/src/Jpp/master/externals/km3net-dataformat/lib:/pbs/throng/km3net/src/Jpp/master/externals/antares-dataformat/:/pbs/throng/km3net/src/Jpp/master/externals/dbclient/lib/:/pbs/throng/km3net/src/Jpp/master/out/Linux/lib/:/pbs/throng/km3net/software/python/3.7.5/lib:/pbs/throng/km3net/software/root/6.20.04/lib:/pbs/software/centos-7-x86_64/xrootd/4.8.1/lib:/pbs/software/centos-7-x86_64/xrootd/4.8.1/lib64:/pbs/software/centos-7-x86_64/oracle/12.2.0/instantclient/lib::/opt/sge/lib/lx-amd64:/opt/sge/lib/lx-amd64
2020-07-15 16:41:17.636954: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: UNKNOWN ERROR (303)
2020-07-15 16:41:17.637005: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ccwsge0449): /proc/driver/nvidia/version does not exist
2020-07-15 16:41:17.637615: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-07-15 16:41:17.673167: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2195000000 Hz
2020-07-15 16:41:17.676580: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5ceefd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-15 16:41:17.676618: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-15 16:41:18.009165: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cwise_ops_common.h:134 : Resource exhausted: OOM when allocating tensor with shape[52224,4096] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Using TensorFlow backend.
Traceback (most recent call last):
  File "/sps/km3net/users/ffilippi/ML/CNN_3d.py", line 45, in <module>
    model.add(Dense(4096,activation="relu"))
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/engine/sequential.py", line 182, in add
    output_tensor = layer(self.outputs[0])
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/layers/core.py", line 895, in build
    constraint=self.kernel_constraint)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/initializers.py", line 227, in __call__
    dtype=dtype, seed=self.seed)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 4357, in random_uniform
    shape, minval=minval, maxval=maxval, dtype=dtype, seed=seed)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/keras/backend.py", line 5686, in random_uniform
    shape, minval=minval, maxval=maxval, dtype=dtype, seed=seed)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 301, in random_uniform
    result = math_ops.add(result * (maxval - minval), minval, name=name)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 984, in binary_op_wrapper
    return func(x, y, name=name)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/ops/math_ops.py", line 1283, in _mul_dispatch
    return gen_math_ops.mul(x, y, name=name)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 6089, in mul
    _ops.raise_from_not_ok_status(e, name)
  File "/pbs/home/f/ffilippi/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[52224,4096] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:Mul]
